"use strict";

// Contenido real del sitio: guías de compra y artículos de blog.
// Nada de datos de producto inventados (ni precios exactos, ni valoraciones,
// ni modelos) en el cuerpo de la guía: son guías de criterio, no fichas de
// producto. Los productos concretos van en el array `products` de cada guía.

const GUIDES = [
  {
    slug: "mancuernas-ajustables",
    title: "Cómo elegir mancuernas para entrenar en casa",
    dek: "Fijas, ajustables o con discos: qué formato compensa según tu nivel y el espacio que tienes.",
    img: "/assets/img/guias/mancuernas-ajustables.jpg",
    updated: "2026-09-15",
    intro: [
      "El error más caro al comprar mancuernas es acertar con el peso de hoy y quedarte corto en tres meses. Progresar en fuerza es el objetivo de cualquier rutina, así que el formato que elijas debería acompañar esa progresión, no obligarte a comprar otra vez.",
      "Esta guía no recomienda un modelo concreto: te da los criterios para que compares cualquier set de mancuernas con cabeza, incluidas las que encuentres en Amazon.",
    ],
    sections: [
      {
        heading: "Mancuernas fijas o ajustables",
        body: [
          "Las mancuernas fijas (un peso por pareja) son más baratas por kilo y no tienen piezas que puedan fallar, pero para cubrir una progresión real necesitas comprar varias parejas, lo que ocupa espacio y acaba costando más que un sistema ajustable equivalente.",
          "Las mancuernas ajustables (de disco selector o de discos apilables) resuelven el problema de espacio y de progresión con una sola pareja, a cambio de un desembolso inicial mayor y de un mecanismo de cambio de peso que conviene probar que sea rápido: algunos sistemas tardan más en cambiar de peso que en hacer la serie.",
        ],
      },
      {
        heading: "Qué rango de peso necesitas de verdad",
        body: [
          "Para tren superior, un rango de 2-24 kg por mancuerna cubre a la mayoría de personas que empiezan y varios años de progresión. Para tren inferior (sentadilla goblet, peso muerto rumano) casi siempre hace falta más peso del que el tren superior necesita, así que si solo vas a comprar un set, prioriza que llegue alto de peso antes que llegue muy bajo.",
          "Comprar un rango justo para el nivel de hoy es la forma más habitual de acabar comprando el mismo producto dos veces: mejor un sistema que tenga recorrido de progresión de al menos 6-12 meses de entrenamiento constante.",
        ],
      },
      {
        heading: "Material y agarre",
        body: [
          "El recubrimiento de goma o neopreno protege el suelo y es más silencioso que el hierro fundido a la vista, importante si entrenas en un piso con vecinos debajo. El diámetro del agarre importa tanto como el peso: una empuñadura demasiado gruesa cansa el antebrazo antes de que el músculo objetivo llegue al fallo.",
        ],
      },
      {
        heading: "Espacio y protección del suelo",
        body: [
          "Incluso las mancuernas ajustables más compactas necesitan un hueco fijo donde vivir, y casi siempre conviene una esterilla o base de goma debajo: no solo protege el suelo de arañazos, también amortigua si se te cae una repetición a media serie.",
        ],
      },
    ],
    checklist: [
      "Rango de peso con recorrido para 6-12 meses de progresión, no solo para hoy",
      "Sistema de cambio de peso rápido si eliges ajustables",
      "Recubrimiento que proteja el suelo y no haga ruido",
      "Diámetro de agarre cómodo para tu mano",
      "Base o esterilla de protección del suelo",
    ],
    faq: [
      {
        q: "¿Merece la pena comprar ajustables si soy principiante?",
        a: "Si tienes claro que vas a seguir entrenando más de unos meses, sí: el ahorro de espacio y el hecho de no tener que volver a comprar cuando progreses suele compensar el precio inicial más alto. Si no estás seguro de mantener el hábito, un par de mancuernas fijas de peso medio es una forma más barata de probar.",
      },
      {
        q: "¿Cuánto peso necesito para empezar?",
        a: "Depende mucho de la persona, pero como referencia orientativa: tren superior entre 4-10 kg por mancuerna y tren inferior entre 10-20 kg suele bastar las primeras semanas. Lo importante no es acertar el número exacto, sino elegir un sistema que puedas subir de peso sin comprar nada nuevo.",
      },
    ],
    products: [
      {
        asin: "B0DKVK1VJW",
        title: "unycos Mancuernas Ajustables 10-40 kg con discos de cemento",
        note: "Entrada de gama: sistema de discos clásico, el más barato por kilo total.",
        img: "https://m.media-amazon.com/images/I/71MIDSrd2SL._AC_SF480,480_.jpg",
        price: "27",
        rating: "4,4★",
      },
      {
        asin: "B0FB3RSTV5",
        title: "Mobiclinic Mancuernas ajustables 2 en 1, 2-30 kg",
        note: "Buen equilibrio precio/rango de peso, con barra de extensión incluida.",
        img: "https://m.media-amazon.com/images/I/812yUVQAz2L._AC_SF480,480_.jpg",
        price: "44",
        rating: "4,5★",
      },
      {
        asin: "B0GL1J72MP",
        title: "FEIERDUN Set 5 en 1, 10-40 kg",
        note: "Varios pares en un solo sistema de discos, buena opción de progresión barata.",
        img: "https://m.media-amazon.com/images/I/71d7fhX3wkL._AC_SF480,480_.jpg",
        price: "49",
        rating: "4,5★",
      },
      {
        asin: "B0DBY1JFVP",
        title: "Mancuernas Ajustables compactas 10 kg, impermeables",
        note: "Formato compacto y rápido de ajustar; buena opción si el espacio manda.",
        img: "https://m.media-amazon.com/images/I/61oQ5DJ+zuL._AC_SF480,480_.jpg",
        price: "69",
        rating: "4,7★",
      },
      {
        asin: "B0GJ61RH56",
        title: "JUPPLIES Mancuerna Ajustable 2-24 kg, 15 niveles",
        note: "Ajuste rápido con bloqueo de seguridad: el mejor punto medio de la selección.",
        img: "https://m.media-amazon.com/images/I/813G91Zl9UL._AC_SF480,480_.jpg",
        price: "119",
        rating: "4,7★",
      },
      {
        asin: "B07PXS7QD3",
        title: "ATIVAFIT Mancuerna Ajustable 25-30 kg, 10-12 niveles",
        note: "Más recorrido de peso para quien ya tiene experiencia levantando.",
        img: "https://m.media-amazon.com/images/I/71nsKVkFINL._AC_SF480,480_.jpg",
        price: "145",
        rating: "4,5★",
      },
      {
        asin: "B0GX968ZXZ",
        title: "SONGMICS Juego de 2 Mancuernas Ajustables 12 en 1",
        note: "Gama alta: máximo recorrido de peso y mango antideslizante de calidad.",
        img: "https://m.media-amazon.com/images/I/71oBHqs8AaL._AC_SF480,480_.jpg",
        price: "170",
        rating: "4,5★",
      },
      {
        asin: "B0D9JFQS7P",
        title: "Amazon Basics Mancuerna ajustable, mancuerna individual",
        note: "Vendida por unidad: útil si necesitas completar un peso concreto sin comprar el par.",
        img: "https://m.media-amazon.com/images/I/61GGtzGzo1L._AC_SF480,480_.jpg",
        price: "107",
        rating: "4,5★",
      },
      {
        asin: "B078XXP3RH",
        title: "Amazon Basics Par de mancuernas de neopreno",
        note: "Mancuernas fijas de entrada: las más baratas si solo quieres probar con poco peso.",
        img: "https://m.media-amazon.com/images/I/81NlaW85aBL._AC_SF480,480_.jpg",
        price: "13",
        rating: "4,7★",
      },
      {
        asin: "B07GSVQGKF",
        title: "SONGMICS Mancuernas Ajustables, Dumbbell Set",
        note: "Sistema de discos económico de marca conocida en accesorios de fitness.",
        img: "https://m.media-amazon.com/images/I/71Siv2KT5jL._AC_SF480,480_.jpg",
        price: "31",
        rating: "4,4★",
      },
      {
        asin: "B0G3ZCYS8F",
        title: "unycos - Mancuernas Ajustables 2,5-25 kg de Acero (Titan Transformer)",
        note: "Construcción en acero en vez del cemento habitual en este rango de precio.",
        img: "https://m.media-amazon.com/images/I/714XAi4FTEL._AC_SF480,480_.jpg",
        price: "49",
        rating: "4,7★",
      },
      {
        asin: "B09YTXX7TK",
        title: "Yaheetech Kit Mancuernas Ajustables con Cerraduras de Estrella",
        note: "Discos con cierre de estrella, rápido de cambiar sin herramientas.",
        img: "https://m.media-amazon.com/images/I/61rQQz8REKL._AC_SF480,480_.jpg",
        price: "45",
        rating: "4,3★",
      },
      {
        asin: "B0DNWW2QX8",
        title: "ManiBoom Mancuernas Ajustables Hierro Puro con Barra Extensora",
        note: "Discos de hierro macizo (no plástico) y maletín rígido de transporte.",
        img: "https://m.media-amazon.com/images/I/71eOXbDJBaL._AC_SF480,480_.jpg",
        price: "63",
        rating: "4,6★",
      },
      {
        asin: "B0GVGDYX6W",
        title: "DH FitLife Mancuernas Ajustables 12/25 kg, 10 Niveles, con Base",
        note: "Incluye base de apoyo propia, útil si no tienes soporte donde dejarlas.",
        img: "https://m.media-amazon.com/images/I/719a5+gqdPL._AC_SF480,480_.jpg",
        price: "179",
        rating: "4,6★",
      },
      {
        asin: "B0D7D6VHC8",
        title: "BRAINGAIN Mancuernas Ajustables Set 23,5/32,5/41,5 kg",
        note: "Gama premium: mango de 34 mm y cambio de peso en un segundo, para quien ya levanta mucho.",
        img: "https://m.media-amazon.com/images/I/61HhezgBFoL._AC_SF480,480_.jpg",
        price: "709",
        rating: "4,6★",
      },
    ],
  },
  {
    slug: "esterillas-yoga",
    title: "Cómo elegir una esterilla de yoga o fitness",
    dek: "Grosor, material y agarre: la diferencia entre una esterilla que se desliza y una que dura años.",
    img: "/assets/img/guias/esterillas-yoga.jpg",
    updated: "2026-09-14",
    intro: [
      "Una esterilla mala se nota en la primera clase de yoga con calor o en la primera serie de burpees: se desliza, se marca o se rompe por los pliegues. El grosor y el material correctos dependen sobre todo de qué vas a hacer sobre ella, no de cuál es \"la mejor\" en general.",
    ],
    sections: [
      {
        heading: "Grosor: equilibrio entre confort y estabilidad",
        body: [
          "Las esterillas finas (3-4 mm) dan más estabilidad en posturas de equilibrio porque el pie no se hunde, y son las que suelen usarse en yoga tradicional. Las gruesas (10-15 mm) amortiguan mejor rodillas y columna en ejercicios de suelo o HIIT, pero restan estabilidad si haces posturas de pie sobre un solo apoyo.",
          "Si vas a usar la misma esterilla para todo (yoga y entrenamiento de fuerza en suelo), un término medio de 6-8 mm suele ser el que menos concesiones exige en ambos usos.",
        ],
      },
      {
        heading: "Material: PVC, TPE o caucho natural",
        body: [
          "El PVC es el más barato y duradero, pero es el menos ecológico y algunas esterillas de PVC desprenden olor los primeros días. El TPE es más ligero y biodegradable, con un agarre intermedio y buena relación calidad-precio. El caucho natural da el mejor agarre, sobre todo con sudor, pero pesa más, cuesta más y puede dar problema a quien tenga alergia al látex.",
        ],
      },
      {
        heading: "Agarre en seco frente a agarre en húmedo",
        body: [
          "Una esterilla que no resbala en seco puede volverse una pista de patinaje en cuanto empiezas a sudar. Si vas a hacer yoga caliente, HIIT o cualquier entrenamiento intenso, prioriza el agarre en húmedo sobre el agarre en seco: es lo que de verdad falla a mitad de sesión.",
        ],
      },
      {
        heading: "Tamaño y portabilidad",
        body: [
          "El tamaño estándar (173 cm) se queda corto para cualquiera por encima de 1,75 m aproximadamente: si es tu caso, busca esterillas de 183 cm o más. Si vas a llevarla a clases fuera de casa, el peso y si trae correa o bolsa de transporte importan tanto como el material.",
        ],
      },
    ],
    checklist: [
      "Grosor según el uso: fino para equilibrio, grueso para impacto en suelo",
      "Material según el agarre que necesitas (caucho natural si sudas mucho)",
      "Talla suficiente para tu altura (183 cm o más si mides más de 1,75 m)",
      "Correa o bolsa si la vas a transportar fuera de casa",
    ],
    faq: [
      {
        q: "¿Qué grosor elijo si hago de todo (yoga y HIIT)?",
        a: "Un punto medio de 6-8 mm es la opción con menos concesiones: suficiente amortiguación para ejercicios de suelo sin restar tanta estabilidad como una esterilla muy gruesa en posturas de equilibrio.",
      },
      {
        q: "¿Las esterillas de PVC son tóxicas?",
        a: "Las esterillas de PVC de fabricantes serios cumplen normativas que limitan ftalatos y metales pesados; busca que lo indique el fabricante (libre de ftalatos, OEKO-TEX u otra certificación similar) si te preocupa especialmente.",
      },
    ],
    products: [
      {
        asin: "B0BH4ZHP9R",
        title: "LA MENTE ES MARAVILLOSA Esterilla de Yoga TPE 183x61",
        note: "Entrada de gama en TPE: ligera, biodegradable y con buen agarre para lo que cuesta.",
        img: "https://m.media-amazon.com/images/I/81yxy0K2ffL._AC_SF480,480_.jpg",
        price: "14",
        rating: "4,6★",
      },
      {
        asin: "B0FPDQJWLR",
        title: "unycos Esterilla de Yoga NBR antideslizante 183x60",
        note: "Material NBR, más acolchado que el TPE básico para el mismo rango de precio.",
        img: "https://m.media-amazon.com/images/I/71MBj8wWCCL._AC_SF480,480_.jpg",
        price: "19",
        rating: "4,6★",
      },
      {
        asin: "B0CS37DGLJ",
        title: "Esterilla Yoga con líneas de alineación",
        note: "Las líneas guía ayudan a colocar manos y pies en posturas de yoga.",
        img: "https://m.media-amazon.com/images/I/71MUol0OBNL._AC_SF480,480_.jpg",
        price: "20",
        rating: "4,6★",
      },
      {
        asin: "B0CYBGQVZH",
        title: "PROIRON Esterilla Yoga, grosor 10/15mm",
        note: "Grosor a elegir: la opción para quien prioriza amortiguación en ejercicios de suelo.",
        img: "https://m.media-amazon.com/images/I/71esx5jQPML._AC_SF480,480_.jpg",
        price: "29",
        rating: "4,7★",
      },
      {
        asin: "B08V1DHP1Y",
        title: "KESSER Esterilla TPE acolchada con correa de transporte",
        note: "Incluye correa: buena opción si te la llevas a clases fuera de casa.",
        img: "https://m.media-amazon.com/images/I/81BeyGj6W6L._AC_SF480,480_.jpg",
        price: "30",
        rating: "4,5★",
      },
      {
        asin: "B0CJJNSM9V",
        title: "Amazon Basics Esterilla extragruesa antideslizante",
        note: "La más gruesa del grupo: prioriza amortiguación sobre estabilidad en equilibrios.",
        img: "https://m.media-amazon.com/images/I/61MOuHsiTRL._AC_SF480,480_.jpg",
        price: "32",
        rating: "4,5★",
      },
      {
        asin: "B0FSK9PBTC",
        title: "Esterilla Yoga Caucho Natural + PU/TPE, líneas de alineación",
        note: "Gama alta: caucho natural para el mejor agarre en húmedo de la selección.",
        img: "https://m.media-amazon.com/images/I/71-DM4htotL._AC_SF480,480_.jpg",
        price: "59",
        rating: "4,5★",
      },
      {
        asin: "B0FY2ZTFK7",
        title: "Yogii Esterilla de Yoga 6 mm Antideslizante TPE Líneas de Alineación",
        note: "Líneas guía de serie en un grosor intermedio de 6 mm.",
        img: "https://m.media-amazon.com/images/I/91+zZUiqaLL._AC_SF480,480_.jpg",
        price: "24",
        rating: "4,3★",
      },
      {
        asin: "B0BZDJ9GGK",
        title: "Esterilla Yoga Antideslizante con Correa de Transporte",
        note: "La opción más barata de la selección, con correa incluida para llevarla fuera.",
        img: "https://m.media-amazon.com/images/I/61sfr+qrOsL._AC_SF480,480_.jpg",
        price: "9",
        rating: "4,5★",
      },
      {
        asin: "B09WDQNHB5",
        title: "Good Nite Esterilla de yoga extra gruesa con correa de transporte",
        note: "Grosor extra pensado para amortiguar más en ejercicios de suelo.",
        img: "https://m.media-amazon.com/images/I/61FT4WHcYdL._AC_SF480,480_.jpg",
        price: "14",
        rating: "4,6★",
      },
      {
        asin: "B0DL3LP6Q5",
        title: "Esterilla Yoga + Pilates + Fitness antideslizante, plegable",
        note: "Formato plegable en vez de enrollado: ocupa menos guardada de canto.",
        img: "https://m.media-amazon.com/images/I/51zNs7ZkgbL._AC_SF480,480_.jpg",
        price: "16",
        rating: "4,5★",
      },
      {
        asin: "B0DKPHTGDR",
        title: "Esterilla Yoga Antideslizante XL 212 x 150 cm",
        note: "Tamaño extra grande: la única de la selección pensada para más de una persona a la vez.",
        img: "https://m.media-amazon.com/images/I/61qZQiHGiKL._AC_SF480,480_.jpg",
        price: "58",
        rating: "4,6★",
      },
      {
        asin: "B0B3NC994H",
        title: "DH FitLife Esterilla de Yoga de Corcho para Fitness",
        note: "Corcho en vez de PVC/TPE/caucho: superficie distinta, más agarre cuanto más sudas.",
        img: "https://m.media-amazon.com/images/I/81LXAuNCZSL._AC_SF480,480_.jpg",
        price: "38",
        rating: "4,2★",
      },
      {
        asin: "B0FW4P2Q72",
        title: "STAASH Set de yoga de alta calidad (esterilla + toalla + correa + almohadilla)",
        note: "Set completo en caucho natural, no solo la esterilla suelta.",
        img: "https://m.media-amazon.com/images/I/71y4aFt4xVL._AC_SF480,480_.jpg",
        price: "79",
        rating: "4,4★",
      },
      {
        asin: "B08QYZRBVG",
        title: "tectake 800850 Colchoneta de gimnasia plegable",
        note: "Colchoneta plegable gruesa, distinta de una esterilla enrollable clásica.",
        img: "https://m.media-amazon.com/images/I/61TdwA9SPGL._AC_SF480,480_.jpg",
        price: "85",
        rating: "4,8★",
      },
    ],
  },
  {
    slug: "bandas-elasticas",
    title: "Bandas elásticas de resistencia: guía para elegir sin liarte",
    dek: "Tubulares, planas o en bucle (mini bands): para qué sirve cada tipo y cuántas necesitas de verdad.",
    img: "/assets/img/guias/bandas-elasticas.jpg",
    updated: "2026-09-13",
    intro: [
      "\"Comprar una banda elástica\" es una simplificación que lleva a comprar la que no toca: hay al menos tres formatos distintos, cada uno pensado para un tipo de ejercicio diferente, y casi nadie necesita solo una.",
    ],
    sections: [
      {
        heading: "Tipos de banda y para qué sirve cada una",
        body: [
          "Las bandas tubulares con asas sustituyen en casa a buena parte de los ejercicios de máquina de gimnasio (remo, press, curl de bíceps): se anclan con el pie o a una puerta y trabajan tirando o empujando contra la resistencia.",
          "Las bandas planas largas, sin asas, se usan sobre todo para movilidad, estiramientos asistidos y para quitar peso corporal en ejercicios como dominadas asistidas. Las mini bands (en bucle, cortas) son las que se colocan alrededor de piernas o tobillos para activar glúteo y cadera antes de entrenar, o como calentamiento.",
        ],
      },
      {
        heading: "Por qué necesitas varios niveles, no una sola banda",
        body: [
          "A diferencia de unas mancuernas, con una banda elástica no puedes \"añadir peso\": para progresar necesitas una banda de más resistencia. Por eso casi todos los sets útiles vienen en 3-5 niveles codificados por color, y comprar una sola banda suelta suele quedarse corta en pocas semanas.",
        ],
      },
      {
        heading: "Materiales: látex frente a sin látex",
        body: [
          "El látex da la elasticidad más suave y es el más barato, pero se degrada con el sol, el sudor ácido y el aceite corporal, y puede causar reacción alérgica en algunas personas. Las mini bands de tela (en lugar de látex) no se enrollan sobre la piel y duran más al lavado, aunque tienen algo menos de recorrido elástico.",
        ],
      },
      {
        heading: "Anclajes y accesorios",
        body: [
          "Un ancla de puerta amplía mucho los ejercicios posibles con bandas tubulares (remo, press de pecho, jalones), porque permite trabajar de pie en lugar de depender solo del propio cuerpo como anclaje. Si vives de alquiler o no quieres marcas en la puerta, hay anclas que se sujetan sin atornillar.",
        ],
      },
    ],
    checklist: [
      "Set de varios niveles de resistencia, no una sola banda suelta",
      "Tipo según objetivo: tubular para fuerza, bucle para activación, plana para movilidad",
      "Material sin látex si tienes piel sensible o alergia",
      "Ancla de puerta si vas a hacer ejercicios de tirón de pie",
    ],
    faq: [
      {
        q: "¿Las bandas elásticas sustituyen a las pesas?",
        a: "Parcialmente. Son muy buenas para empezar, viajar o hacer activación muscular, pero la resistencia que puedes progresar con bandas tiene un techo más bajo que con pesas a largo plazo. Como complemento o como única opción en espacio reducido funcionan bien; como sustituto permanente de un entrenamiento de fuerza serio, tienen límites.",
      },
      {
        q: "¿Cuánto duran las bandas de látex?",
        a: "Depende mucho de la exposición al sol y del cuidado: guardarlas lejos de luz directa y limpiarlas del sudor alarga su vida. En cuanto una banda muestre grietas o puntos blanquecinos, hay que cambiarla: es la señal de que puede romperse durante el ejercicio.",
      },
    ],
    products: [
      {
        asin: "B0CPSD21L4",
        title: "GRIFEMA GA5002 Bandas elásticas tubulares, set de 4",
        note: "Entrada de gama: set tubular básico para empezar a sustituir máquinas de gimnasio.",
        img: "https://m.media-amazon.com/images/I/71gKwEtS1wL._AC_SF480,480_.jpg",
        price: "7",
        rating: "4,5★",
      },
      {
        asin: "B01FN7XAYW",
        title: "Amazon Basics Banda elástica de resistencia y dominadas",
        note: "Banda plana larga: la opción para movilidad y dominadas asistidas.",
        img: "https://m.media-amazon.com/images/I/61796TWs-kL._AC_SF480,480_.jpg",
        price: "9",
        rating: "4,4★",
      },
      {
        asin: "B0H4GMM4TX",
        title: "Set de 5 bandas elásticas, varios niveles de resistencia",
        note: "La mejor valoración del grupo; set completo de niveles para progresar.",
        img: "https://m.media-amazon.com/images/I/71ZFWYmPjZL._AC_SF480,480_.jpg",
        price: "16",
        rating: "4,8★",
      },
      {
        asin: "B08BJJ8SMD",
        title: "PLEASION Mini bands de tela, set de 5",
        note: "Bucle de tela, sin látex: no se enrolla sobre la piel y dura más al lavado.",
        img: "https://m.media-amazon.com/images/I/81f6nR2TG6L._AC_SF480,480_.jpg",
        price: "15",
        rating: "4,6★",
      },
      {
        asin: "B0GYCQN48D",
        title: "Banda de resistencia con pedales, 3 niveles",
        note: "Pensada para abdomen y piernas trabajando desde el suelo, con guía de ejercicios.",
        img: "https://m.media-amazon.com/images/I/811L2UaSjsL._AC_SF480,480_.jpg",
        price: "23",
        rating: "4,4★",
      },
      {
        asin: "B0D1DV9NHZ",
        title: "Fokky Bandas elásticas con anclaje de puerta y asas",
        note: "Incluye ancla de puerta: amplía mucho los ejercicios de tirón de pie.",
        img: "https://m.media-amazon.com/images/I/71lz3Nq7-OL._AC_SF480,480_.jpg",
        price: "22",
        rating: "4,3★",
      },
      {
        asin: "B0F43BMK4L",
        title: "POWER GUIDANCE Set de 6 con bolsa de transporte",
        note: "Gama alta: seis niveles de resistencia pensados para powerlifting y fuerza.",
        img: "https://m.media-amazon.com/images/I/71p4TYauZ-L._AC_SF480,480_.jpg",
        price: "24",
        rating: "4,3★",
      },
      {
        asin: "B0D7ZMZ4C2",
        title: "Fokky Gomas Elasticas Musculacion con 4 Niveles de Resistencia, 5-85 LBS",
        note: "Cuatro niveles tubulares con asas, buen punto de entrada para tirón y empuje.",
        img: "https://m.media-amazon.com/images/I/71alxj1obnL._AC_SF480,480_.jpg",
        price: "19",
        rating: "4,3★",
      },
      {
        asin: "B0G1MM4ZLL",
        title: "SURFOU Gomas Elasticas Musculacion 4 Niveles",
        note: "Mejor valorada de este rango de precio entre las bandas tubulares con asas.",
        img: "https://m.media-amazon.com/images/I/71kmpAkttNL._AC_SF480,480_.jpg",
        price: "22",
        rating: "4,6★",
      },
      {
        asin: "B0DDL1QN2Q",
        title: "Fokky Gomas Elasticas Musculacion [Set of 3], 8-65LBS",
        note: "Set reducido de solo 3 niveles: opción más compacta para quien no necesita tanto rango.",
        img: "https://m.media-amazon.com/images/I/71DMXBSedJL._AC_SF480,480_.jpg",
        price: "14",
        rating: "4,4★",
      },
      {
        asin: "B0FCTZ9SYV",
        title: "Bandas Elasticas Musculacion, Set de Gomas Elasticas",
        note: "Set genérico de resistencia media, alternativa a las marcas más conocidas.",
        img: "https://m.media-amazon.com/images/I/918xz+RaPbL._AC_SF480,480_.jpg",
        price: "19",
        rating: "4,5★",
      },
      {
        asin: "B09CTVQWK8",
        title: "Fokky Gomas Elasticas Musculacion [Set de 5], Látex Natural",
        note: "La más barata de la selección con cinco niveles ya incluidos.",
        img: "https://m.media-amazon.com/images/I/51sVFEQCXXL._AC_SF480,480_.jpg",
        price: "6",
        rating: "4,4★",
      },
      {
        asin: "B0DWFSMY2F",
        title: "Set de Bandas elasticas 12 Piezas con Tobilleras y Guía de Entrenamiento",
        note: "El kit más completo: añade tobilleras y guía impresa a las bandas tubulares.",
        img: "https://m.media-amazon.com/images/I/71avsrJnDDL._AC_SF480,480_.jpg",
        price: "22",
        rating: "4,1★",
      },
      {
        asin: "B0CPF41NRM",
        title: "Fokky 2M Gomas Elasticas Musculacion, 4 Niveles",
        note: "Formato de 2 metros, más largo que el tubular estándar para más variedad de anclaje.",
        img: "https://m.media-amazon.com/images/I/61NQKfinTvL._AC_SF480,480_.jpg",
        price: "7",
        rating: "4,4★",
      },
      {
        asin: "B0FJM7V4D6",
        title: "Bandas Elásticas de Resistencia de Látex Natural, Juego de 4 Niveles",
        note: "La mejor valoración del grupo; pensada también para fisioterapia y rehabilitación.",
        img: "https://m.media-amazon.com/images/I/51OzDVYVqNL._AC_SF480,480_.jpg",
        price: "29",
        rating: "4,8★",
      },
    ],
  },
  {
    slug: "banco-entrenamiento",
    title: "Banco de entrenamiento plegable: qué mirar antes de comprar",
    dek: "Inclinación, peso máximo soportado y plegado: lo que marca la diferencia en un banco para casa.",
    img: "/assets/img/guias/banco-entrenamiento.jpg",
    updated: "2026-09-12",
    intro: [
      "Un banco de entrenamiento es de las pocas piezas de equipamiento casero que, si falla, falla con peso encima. Por eso los criterios que importan aquí no son solo de comodidad: son también de seguridad.",
    ],
    sections: [
      {
        heading: "Plano, inclinable o multiposición",
        body: [
          "Un banco plano es el más barato y estable, pero limita los ejercicios a variantes planas (press plano, remo con apoyo). Un banco inclinable o multiposición permite trabajar press inclinado y declinado, hombro sentado y más variedad de ejercicios, y en la mayoría de casos compensa el sobrecoste si vas a entrenar en casa a medio plazo.",
        ],
      },
      {
        heading: "Peso máximo soportado, con margen",
        body: [
          "La capacidad de peso indicada por el fabricante debe cubrir tu peso corporal más la carga que vas a levantar, con margen de seguridad: un banco justo de capacidad es un banco que vas a acabar sustituyendo en cuanto progreses. Para press con barra o mancuernas pesadas, prioriza bancos con capacidades claramente por encima de lo que vayas a mover.",
        ],
      },
      {
        heading: "Estabilidad y mecanismo de plegado",
        body: [
          "Un banco que se tambalea bajo carga es un riesgo real, no solo una molestia: revisa el grosor del tubo del armazón y el ancho de la base de apoyo, no solo si pliega o no. El plegado ahorra espacio, pero las bisagras son la pieza que más se afloja con el tiempo y el uso intensivo, así que conviene que el mecanismo de bloqueo en posición sea firme, no solo un pestillo simple.",
        ],
      },
      {
        heading: "Tapizado y comodidad",
        body: [
          "La densidad de la espuma influye en la comodidad en series largas, y el tipo de tapizado (vinilo o similar al cuero) en la durabilidad frente a sudor y roces. Un tapizado fino se agrieta antes con el uso frecuente que uno de mayor grosor.",
        ],
      },
    ],
    checklist: [
      "Capacidad de peso con margen sobre tu peso corporal más la carga",
      "Inclinación regulable si quieres variedad de ejercicios",
      "Base ancha y armazón robusto, no solo \"que pliegue\"",
      "Tapizado resistente que no se agriete con el uso",
    ],
    faq: [
      {
        q: "¿Necesito un banco inclinable o me vale uno plano?",
        a: "Si solo vas a hacer press plano y ejercicios con apoyo horizontal, un banco plano basta y es más barato y estable. En cuanto quieras trabajar hombro o variar el ángulo de pecho, el banco inclinable amplía mucho las opciones por una diferencia de precio que suele merecer la pena.",
      },
      {
        q: "¿Cuánto peso tiene que soportar de verdad?",
        a: "Suma tu peso corporal más el peso máximo que esperas levantar apoyado en el banco (por ejemplo, press con mancuernas pesadas) y añade un margen de seguridad. Un banco anunciado \"justo\" para ese número no es la mejor idea a medio plazo si tu objetivo es progresar en fuerza.",
      },
    ],
    products: [
      {
        asin: "B0GSYX9T71",
        title: "Banco de pesas regulable, 300 kg, 8 posiciones",
        note: "Entrada de gama con capacidad ya generosa y varias posiciones de respaldo.",
        img: "https://m.media-amazon.com/images/I/719zG2ZrQzL._AC_SF480,480_.jpg",
        price: "56",
        rating: "4,5★",
      },
      {
        asin: "B09V8BNQSZ",
        title: "YOLEO Banco de Pesas Ajustable, plano/inclinado/declinado",
        note: "Cubre los tres ángulos que menciona esta guía por un precio medio.",
        img: "https://m.media-amazon.com/images/I/71c-zmsrR5L._AC_SF480,480_.jpg",
        price: "79",
        rating: "4,6★",
      },
      {
        asin: "B0H1QNYMFZ",
        title: "FLYBIRD Banco de pesas ajustable, 300 kg",
        note: "Marca muy valorada en bancos plegables; buena estabilidad para su precio.",
        img: "https://m.media-amazon.com/images/I/71myH9z4CML._AC_SF480,480_.jpg",
        price: "85",
        rating: "4,4★",
      },
      {
        asin: "B09NWDYLZS",
        title: "DH FitLife Banco de pesas plegable, inclinado y plano",
        note: "Incluye entrenador de espalda y abdominales integrado.",
        img: "https://m.media-amazon.com/images/I/612NnHhmk5L._AC_SF480,480_.jpg",
        price: "114",
        rating: "4,2★",
      },
      {
        asin: "B09LLVMDW4",
        title: "PASYOU Banco de pesas ajustable, doble marco, sin montaje",
        note: "Capacidad muy alta (660 lb) y doble marco: pensado para cargas serias.",
        img: "https://m.media-amazon.com/images/I/61d3NSDfOjL._AC_SF480,480_.jpg",
        price: "139",
        rating: "4,6★",
      },
      {
        asin: "B09FPBLSS6",
        title: "JOROTO MD60 Banco de pesas ajustable, 360 kg",
        note: "Gama alta: máxima capacidad de la selección y estructura más robusta.",
        img: "https://m.media-amazon.com/images/I/61bq1obGgyL._AC_SF480,480_.jpg",
        price: "179",
        rating: "4,6★",
      },
      {
        asin: "B0FJX3C4KG",
        title: "Banco de Pesas Ajustable, gama premium",
        note: "El más completo del grupo, para quien monta un rincón de fuerza serio en casa.",
        img: "https://m.media-amazon.com/images/I/71lOb-qGqdL._AC_SF480,480_.jpg",
        price: "349",
        rating: "4,2★",
      },
      {
        asin: "B0GJM7FR2K",
        title: "EveryKip Banco de Musculación Ajustable y Plegable 7 en 1",
        note: "El más económico del grupo; capacidad más justa, adecuado para empezar.",
        img: "https://m.media-amazon.com/images/I/71-4DJGRFhL._AC_SF480,480_.jpg",
        price: "49",
        rating: "4,0★",
      },
      {
        asin: "B071WPLVGZ",
        title: "ISE Banco de Pesas Musculación Ajustable Plegable Multifuncional Reclinable",
        note: "Cubre plano, declinado e inclinado con respaldo reclinable, precio ajustado.",
        img: "https://m.media-amazon.com/images/I/61hQeq0sIOL._AC_SF480,480_.jpg",
        price: "51",
        rating: "4,2★",
      },
      {
        asin: "B0CF2CR7FQ",
        title: "Banco de Ejercicio o Musculación Plegable Ligero Multifunción",
        note: "Formato ligero y plegable, pensado para quien prioriza guardarlo rápido.",
        img: "https://m.media-amazon.com/images/I/51Vs330d+UL._AC_SF480,480_.jpg",
        price: "56",
        rating: "4,5★",
      },
      {
        asin: "B0CLRYN7BX",
        title: "Mobiclinic Banco de musculación plegable, Flexfit",
        note: "Asiento y respaldo regulables por separado, buena nota para su precio medio.",
        img: "https://m.media-amazon.com/images/I/51+TZ+MdQkL._AC_SF480,480_.jpg",
        price: "65",
        rating: "4,6★",
      },
      {
        asin: "B0DSG9CCRR",
        title: "ManiBoom Banco Musculación Plegable con 8 Posiciones",
        note: "Incluye cojín para bíceps y bandas elásticas de regalo, capacidad de 250 kg.",
        img: "https://m.media-amazon.com/images/I/615o9I39V2L._AC_SF480,480_.jpg",
        price: "69",
        rating: "4,3★",
      },
      {
        asin: "B08JLYFX3Q",
        title: "YOLEO Banco de Pesas Ajustable Plegable, Plano/Inclinado/Declinado",
        note: "Cuerpo completo con los tres ángulos y buena valoración en este tramo de precio.",
        img: "https://m.media-amazon.com/images/I/81GBn0uijGL._AC_SF480,480_.jpg",
        price: "99",
        rating: "4,6★",
      },
      {
        asin: "B071WRNDWH",
        title: "ISE Banco de Musculación Multifuncional Inclinable",
        note: "Estructura más robusta que las de gama media, pero capacidad máxima algo menor (120 kg).",
        img: "https://m.media-amazon.com/images/I/61ckTlseFWS._AC_SF480,480_.jpg",
        price: "116",
        rating: "4,0★",
      },
      {
        asin: "B09V282W3K",
        title: "JOROTO MD35 Banco de Pesas Ajustable, carga de 318 kg",
        note: "Bloqueo automático de ajuste rápido y capacidad muy alta para cuerpo completo.",
        img: "https://m.media-amazon.com/images/I/71QAQHcTEVL._AC_SF480,480_.jpg",
        price: "119",
        rating: "4,6★",
      },
    ],
  },
  {
    slug: "accesorios-cardio",
    title: "Comba de saltar y accesorios de cardio para entrenar en casa",
    dek: "Qué accesorios de cardio realmente aportan algo y cuáles son solo complemento.",
    img: "/assets/img/guias/accesorios-cardio.jpg",
    updated: "2026-09-10",
    intro: [
      "La comba de saltar es de los accesorios de cardio con mejor relación precio-resultado que existen, pero elegir mal el tipo o la longitud es la razón más habitual de que acabe en un cajón a la semana.",
    ],
    sections: [
      {
        heading: "Comba de cable, PVC o lastrada",
        body: [
          "Las combas de cable fino están pensadas para velocidad y dobles saltos, y son las que usa quien ya tiene técnica. Las de PVC son más lentas y fáciles de controlar, mejor punto de entrada para quien empieza. Las lastradas añaden peso al mango o al cable para trabajar más hombro y antebrazo, pero son más exigentes para la muñeca si no tienes ya una base.",
        ],
      },
      {
        heading: "El ajuste de longitud, la parte que casi nadie mira",
        body: [
          "Una comba demasiado larga se engancha en los pies constantemente; demasiado corta obliga a saltar más alto de lo necesario y castiga la técnica. La referencia rápida: de pie sobre el centro de la cuerda, los mangos deben llegarte aproximadamente a la altura de las axilas.",
        ],
      },
      {
        heading: "Guantes y muñequeras: cuándo aportan algo",
        body: [
          "Los guantes de levantamiento ayudan a proteger la piel en ejercicios de agarre intenso (dominadas, remo con barra), pero reducen el contacto directo con la barra, lo que a algunas personas les resta sensación de control. Las muñequeras ayudan sobre todo en press pesado por encima de la cabeza; para cardio ligero como la comba no suelen ser necesarias.",
        ],
      },
      {
        heading: "El suelo importa tanto como el accesorio",
        body: [
          "Saltar a la comba sobre suelo duro sin ninguna amortiguación aumenta el impacto en las articulaciones y el ruido hacia el piso de abajo. Unas losetas de goma entrelazables resuelven ambos problemas a la vez y son útiles para cualquier ejercicio de impacto, no solo la comba.",
        ],
      },
    ],
    checklist: [
      "Comba ajustada a tu altura (mango a la altura de la axila, de pie sobre la cuerda)",
      "Tipo de cable según tu nivel: PVC para iniciarte, cable fino para velocidad",
      "Suelo amortiguado si saltas sobre piso duro",
      "Guantes o muñequeras solo si tu entrenamiento realmente lo justifica",
    ],
    faq: [
      {
        q: "¿Qué comba elijo si soy principiante?",
        a: "Una de PVC o con cuentas (beaded), más lenta y fácil de controlar mientras coges el ritmo y la coordinación. Las combas de cable fino para velocidad tienen más curva de aprendizaje y se disfrutan más cuando ya dominas la técnica básica.",
      },
      {
        q: "¿Necesito una esterilla anti-impacto además de mi esterilla normal?",
        a: "Si saltas a la comba con frecuencia o vives en un piso con vecinos debajo, sí: una esterilla de yoga normal no está pensada para absorber impacto repetido y no protege el suelo del ruido igual que unas losetas de goma más gruesas.",
      },
    ],
    products: [
      {
        asin: "B0D1QCBPP7",
        title: "GRIFEMA GA5004 Comba para saltar, cuerda 2.8m",
        note: "Comba de PVC básica: fácil de controlar para quien empieza.",
        img: "https://m.media-amazon.com/images/I/61UAIOq+8XL._AC_SF480,480_.jpg",
        price: "5",
        rating: "4,5★",
      },
      {
        asin: "B08CRVG7BB",
        title: "Blukar Cuerda para saltar, longitud ajustable",
        note: "Ajuste libre de longitud, la parte que más se suele pasar por alto.",
        img: "https://m.media-amazon.com/images/I/71VL-JqH5VL._AC_SF480,480_.jpg",
        price: "6",
        rating: "4,4★",
      },
      {
        asin: "B0BR4Z75FB",
        title: "PROIRON Cuerda de saltar, mango de aluminio",
        note: "Punto medio: cable más rápido que el PVC sin llegar a nivel de competición.",
        img: "https://m.media-amazon.com/images/I/810+o2NIVwL._AC_SF480,480_.jpg",
        price: "15",
        rating: "4,4★",
      },
      {
        asin: "B0F9YTT9YN",
        title: "PICSIL Rook, comba rápida de aluminio",
        note: "Gama alta para dobles saltos y técnica avanzada, cable de velocidad.",
        img: "https://m.media-amazon.com/images/I/61SJJkyk+lL._AC_SF480,480_.jpg",
        price: "32",
        rating: "4,5★",
      },
      {
        asin: "B07KQP1X5T",
        title: "ATERCEL Guantes de gimnasio, transpirables",
        note: "Para proteger la piel en ejercicios de agarre intenso (dominadas, barra).",
        img: "https://m.media-amazon.com/images/I/71Qa99mgPPL._AC_SF480,480_.jpg",
        price: "9",
        rating: "4,6★",
      },
      {
        asin: "B0FPD4QFVQ",
        title: "RDX Guantes con muñequera de 3 placas",
        note: "Combina guante y soporte de muñeca para press pesado por encima de la cabeza.",
        img: "https://m.media-amazon.com/images/I/81glRlHJtrL._AC_SF480,480_.jpg",
        price: "22",
        rating: "4,0★",
      },
      {
        asin: "B0G2MSQNCJ",
        title: "JUPPLIES Suelo Gimnasio puzzle de goma, 12 piezas",
        note: "Losetas amortiguadoras: reducen impacto en articulaciones y ruido hacia el vecino de abajo.",
        img: "https://m.media-amazon.com/images/I/81QHE+HQyiL._AC_SF480,480_.jpg",
        price: "18",
        rating: "4,6★",
      },
      {
        asin: "B07TCNBG5Y",
        title: "Amazon Basics Standard Jump Rope",
        note: "Comba de PVC básica de marca genérica fiable, fácil de controlar para empezar.",
        img: "https://m.media-amazon.com/images/I/81wdb6hG6iL._AC_SF480,480_.jpg",
        price: "5",
        rating: "4,4★",
      },
      {
        asin: "B0FQJQL1JM",
        title: "PICSIL Sphinx, Comba Rápida y Ligera",
        note: "Cable de velocidad para todos los niveles, un peldaño por debajo de la PICSIL Rook.",
        img: "https://m.media-amazon.com/images/I/61jvE4xwBmL._AC_SF480,480_.jpg",
        price: "28",
        rating: "4,5★",
      },
      {
        asin: "B08PVWPB4D",
        title: "Comba Crossfit Boxeo Cuerda Saltar Velocidad con Pesos",
        note: "Cable con peso añadido: exige más de hombro y antebrazo que una comba estándar.",
        img: "https://m.media-amazon.com/images/I/71EaV9mKomL._AC_SF480,480_.jpg",
        price: "26",
        rating: "4,4★",
      },
      {
        asin: "B07S1DPX9L",
        title: "Grebarley Guantes Gimnasio, transpirables con protección de muñeca",
        note: "Protección de muñeca integrada además de la palma, útil en ejercicios de empuje.",
        img: "https://m.media-amazon.com/images/I/71CimBMOZYL._AC_SF480,480_.jpg",
        price: "18",
        rating: "4,4★",
      },
      {
        asin: "B07S76NGNQ",
        title: "Roar Muñequeras Deportivas (2 unidades)",
        note: "Solo muñequera, sin guante: para quien no necesita proteger la palma.",
        img: "https://m.media-amazon.com/images/I/713OsssJYtL._AC_SF480,480_.jpg",
        price: "10",
        rating: "4,5★",
      },
      {
        asin: "B01D92OIGM",
        title: "Guantes de Pesas Mava con Soporte de Muñeca",
        note: "Gama alta de guantes con muñequera integrada, pensado para cross training.",
        img: "https://m.media-amazon.com/images/I/81l5ZOkfzNL._AC_SF480,480_.jpg",
        price: "25",
        rating: "4,3★",
      },
      {
        asin: "B0CNG8MDWB",
        title: "AIRHOP 12 pzs Suelo Gimnasio Mejorado para Equipo Pesado",
        note: "Goma extra gruesa pensada para equipo pesado, no solo para saltar a la comba.",
        img: "https://m.media-amazon.com/images/I/71Qi188ePVL._AC_SF480,480_.jpg",
        price: "149",
        rating: "4,6★",
      },
      {
        asin: "B0D9MBKXMM",
        title: "EDIESI Suelo Gimnasio Tatami",
        note: "Formato tatami en vez de puzzle de goma: alternativa más barata para el mismo problema de impacto.",
        img: "https://m.media-amazon.com/images/I/71A5V5E-Z+L._AC_SF480,480_.jpg",
        price: "23",
        rating: "4,3★",
      },
    ],
  },
  {
    slug: "kettlebells",
    title: "Kettlebells: cómo elegir una pesa rusa para entrenar en casa",
    dek: "Fija, ajustable, de hierro fundido o revestida en neopreno: qué formato compensa según el ejercicio que quieras hacer.",
    img: "/assets/img/guias/kettlebells.jpg",
    updated: "2026-09-17",
    intro: [
      "Una kettlebell no es una mancuerna con forma rara: el peso descentrado respecto al agarre es justo lo que la hace útil para movimientos balísticos (swing, snatch, clean) que con una mancuerna normal resultan incómodos o directamente peligrosos.",
      "Esta guía no recomienda un modelo concreto: te da los criterios para comparar cualquier kettlebell, incluidas las que encuentres en Amazon, antes de decidir cuál compensa según tu nivel.",
    ],
    sections: [
      {
        heading: "Fija, ajustable o de relleno regulable",
        body: [
          "Las kettlebells fijas (hierro fundido de una sola pieza) son las más robustas y las que mejor imitan la sensación de una pesa rusa de gimnasio, pero para progresar necesitas comprar varias, lo que ocupa espacio y sale más caro a largo plazo.",
          "Las ajustables de varios niveles resuelven el problema de espacio con una sola pieza, a cambio de un mecanismo de cambio de peso que conviene que sea rápido y seguro bajo movimiento: en un swing o un snatch, una pieza mal bloqueada es un riesgo real, no solo una molestia.",
        ],
      },
      {
        heading: "Material: hierro fundido, vinilo o revestimiento suave",
        body: [
          "El hierro fundido sin recubrir es el más duradero y el más barato por kilo, pero puede dañar el suelo si se golpea y resulta más ruidoso. El revestimiento de vinilo o neopreno protege el suelo, reduce el ruido de impacto y suele venir codificado por color según el peso, útil si vas a tener varias.",
          "Las kettlebells de relleno blando (arena o similar dentro de una carcasa de PVC o goma) son más baratas y silenciosas, buena opción de entrada, pero tienen menos sensación de \"pesa maciza\" que el hierro fundido en movimientos rápidos.",
        ],
      },
      {
        heading: "El agarre importa más que en unas mancuernas",
        body: [
          "En swings, snatches y otros movimientos balísticos, la kettlebell pasa por la mano en cada repetición: un asa demasiado gruesa, con bordes ásperos o mal acabada acaba dañando la palma antes de que el ejercicio canse el músculo objetivo. Un asa ancha y lisa, con espacio suficiente para las dos manos en el swing a dos manos, es un criterio que casi nadie mira al comprar y que se nota mucho en la práctica.",
        ],
      },
      {
        heading: "Qué peso elegir para empezar",
        body: [
          "Como referencia orientativa y sin sustituir la valoración de un profesional: para mujeres que empiezan, 8-12 kg suele bastar para aprender la técnica del swing; para hombres, 12-16 kg. Es preferible empezar algo bajo de peso y centrarse en la técnica que comprar una kettlebell pesada y compensar con mala forma, sobre todo en movimientos con impulso como el swing.",
        ],
      },
    ],
    checklist: [
      "Formato según tu prioridad: fija para sensación clásica, ajustable para ahorrar espacio",
      "Revestimiento (vinilo o neopreno) si te preocupa proteger el suelo o el ruido",
      "Asa ancha y lisa, sin bordes que dañen la palma en movimientos repetidos",
      "Peso de entrada moderado: mejor progresar en técnica que empezar con demasiado peso",
    ],
    faq: [
      {
        q: "¿Una kettlebell sustituye a las mancuernas?",
        a: "No del todo: son complementarias. La kettlebell está pensada sobre todo para movimientos balísticos y de cadera (swing, clean, snatch), mientras que las mancuernas cubren mejor el trabajo analítico de un músculo concreto (curl, press, elevaciones). Si solo puedes elegir una, depende de qué tipo de entrenamiento prefieras.",
      },
      {
        q: "¿Merece la pena una kettlebell ajustable?",
        a: "Si el espacio es el problema principal, sí: una sola pieza cubre varios pesos. Si lo que buscas es la sensación más parecida a una kettlebell de gimnasio para movimientos rápidos, una fija de hierro fundido suele dar mejor tacto que el mecanismo de una ajustable.",
      },
    ],
    products: [
      {
        asin: "B0FV96VT5X",
        title: "Pesa Rusa Kettlebell Fabricada en España, 3 a 14 kg",
        note: "Entrada de gama más barata de la selección, con agarre ergonómico y base estable.",
        img: "https://m.media-amazon.com/images/I/518JFnStGxL._AC_SF480,480_.jpg",
        price: "12",
        rating: "4,2★",
      },
      {
        asin: "B0DFHND2SR",
        title: "ManiBoom Pesas Rusas PVC Suave (2-12 kg)",
        note: "Relleno de arena insonorizado: la opción más silenciosa y que menos daña el suelo.",
        img: "https://m.media-amazon.com/images/I/51LGVRFHUnL._AC_SF480,480_.jpg",
        price: "18",
        rating: "4,8★",
      },
      {
        asin: "B0BSX8Q1HC",
        title: "unycos Pesa Rusa Kettlebell de Hierro Fundido 4-20 kg",
        note: "Hierro fundido clásico a precio de entrada, sin revestimiento.",
        img: "https://m.media-amazon.com/images/I/818nqhdoJNL._AC_SF480,480_.jpg",
        price: "16",
        rating: "4,8★",
      },
      {
        asin: "B0722Y11Z3",
        title: "Sveltus Pesa Rusa para Fitness, 6 kg",
        note: "Kettlebell fija revestida por color según el peso, formato clásico de estudio de fitness.",
        img: "https://m.media-amazon.com/images/I/81bxu2xU4HL._AC_SF480,480_.jpg",
        price: "19",
        rating: "4,5★",
      },
      {
        asin: "B072HX1ZJS",
        title: "Sveltus Pesa Rusa para Fitness, 8 kg",
        note: "Mismo sistema que la Sveltus de 6 kg, un peso más para progresar sin cambiar de marca.",
        img: "https://m.media-amazon.com/images/I/71xp7WJNTcL._AC_SF480,480_.jpg",
        price: "24",
        rating: "4,3★",
      },
      {
        asin: "B0BPYVWR5N",
        title: "Cecotec Pesa Rusa Drumfit KettleBell Neo, 8-10-12 kg",
        note: "Revestimiento de neopreno de fácil limpieza, buen punto medio de precio.",
        img: "https://m.media-amazon.com/images/I/516P3cpZ0BL._AC_SF480,480_.jpg",
        price: "29",
        rating: "4,3★",
      },
      {
        asin: "B076QJY2FN",
        title: "Amazon Basics Kettlebell de Hierro Fundido, agarre ancho",
        note: "Agarre ancho texturizado, uno de los criterios más importantes de esta guía.",
        img: "https://m.media-amazon.com/images/I/71aPoeZThIL._AC_SF480,480_.jpg",
        price: "30",
        rating: "4,7★",
      },
      {
        asin: "B071VMCNG1",
        title: "Sveltus Pesa Rusa para Fitness, 12 kg",
        note: "Tercer peso de la misma gama Sveltus para completar una progresión de varios kilos.",
        img: "https://m.media-amazon.com/images/I/816ntAkl-GL._AC_SF480,480_.jpg",
        price: "31",
        rating: "4,0★",
      },
      {
        asin: "B0FXDX5P9H",
        title: "SPORTNOW Pesa Rusa Soft Kettlebell, 4/6/8/10/12 kg",
        note: "Revestimiento blando en todo el cuerpo, pensada para no dañar el suelo en caídas.",
        img: "https://m.media-amazon.com/images/I/51IbCtTV+rL._AC_SF480,480_.jpg",
        price: "39",
        rating: "4,7★",
      },
      {
        asin: "B09DPLN4FG",
        title: "Yaheetech Juego de Pesa Rusa de Hormigón, 2/4/6/8 kg",
        note: "Juego de varios pesos en una sola compra, formato de hormigón revestido.",
        img: "https://m.media-amazon.com/images/I/716mBBx9BbL._AC_SF480,480_.jpg",
        price: "56",
        rating: "4,2★",
      },
      {
        asin: "B0B6ZTP42T",
        title: "Kettlebell de Competición Viok Sport",
        note: "Estándar de competición con diámetro de asa constante entre pesos: pensada para progresar en técnica sin que cambie el agarre.",
        img: "https://m.media-amazon.com/images/I/41M2IV9bk8L._AC_SF480,480_.jpg",
        price: "59",
        rating: "5,0★",
      },
      {
        asin: "B0FQTZJTD2",
        title: "HXD-ERGO Kettlebell Ajustable 6 en 1 (3-18 kg)",
        note: "Cambio de peso rápido con un solo sistema: la opción para ahorrar espacio con varios niveles.",
        img: "https://m.media-amazon.com/images/I/716TazAwL-L._AC_SF480,480_.jpg",
        price: "99",
        rating: "4,4★",
      },
      {
        asin: "B0FW4YW6X5",
        title: "LIFERUN Kettlebell Ajustable 20 kg, 7 niveles",
        note: "Gama alta: mayor peso máximo y más niveles de ajuste que las ajustables más baratas.",
        img: "https://m.media-amazon.com/images/I/61w58KCW7zL._AC_SF480,480_.jpg",
        price: "119",
        rating: "4,4★",
      },
    ],
  },
  {
    slug: "rodillos-espuma-recuperacion",
    title: "Rodillo de espuma (foam roller): cómo elegir el tuyo",
    dek: "Densidad, tamaño y superficie: lo que de verdad cambia entre un rodillo de 10 € y uno de 150 €.",
    img: "/assets/img/guias/rodillos-espuma-recuperacion.jpg",
    updated: "2026-09-18",
    intro: [
      "El rodillo de espuma sirve para liberación miofascial: presionar y rodar sobre un músculo cargado para aflojarlo, algo especialmente útil después de entrenar con pesas o correr. No sustituye al estiramiento ni a un fisioterapeuta, pero es de los accesorios más baratos que puedes tener en casa para recuperación.",
      "Esta guía no recomienda un modelo concreto: te da los criterios para comparar cualquier rodillo de espuma, incluidos los que encuentres en Amazon.",
    ],
    sections: [
      {
        heading: "Densidad: blando, medio o firme",
        body: [
          "Un rodillo blando (espuma de baja densidad) es más cómodo para empezar y para zonas sensibles, pero se deforma con el uso y aporta menos presión real sobre el músculo. Un rodillo firme (EPP o EVA de alta densidad) mantiene la forma con el tiempo y da más presión, pero puede resultar excesivo si nunca has usado uno.",
          "Los rodillos con relieve o puntos de presión (tipo \"trigger point\") concentran la presión en zonas concretas, útiles si ya sabes localizar dónde tienes más tensión; si es tu primer rodillo, uno liso de densidad media es más fácil de tolerar.",
        ],
      },
      {
        heading: "Tamaño: largo, corto o de viaje",
        body: [
          "Un rodillo largo (60 cm o más) es más estable para espalda y piernas porque no se te escapa por los lados, pero ocupa más espacio guardado. Los rodillos cortos o mini (unos 15 cm) son más manejables para zonas concretas (gemelo, antebrazo) y para llevar de viaje, aunque piden más equilibrio al usarlos en zonas grandes como la espalda.",
        ],
      },
      {
        heading: "Rodillo simple frente a sets con accesorios",
        body: [
          "Muchos sets combinan el rodillo con bolas de masaje o un rodillo más pequeño para zonas puntuales (planta del pie, cuello, antebrazo): si solo vas a trabajar espalda y piernas, un rodillo simple basta y sale más barato. Si buscas cubrir también manos, pies o cuello, un set con varios accesorios evita comprar cada pieza por separado.",
        ],
      },
      {
        heading: "Cuándo un rodillo con vibración o eléctrico compensa",
        body: [
          "Los rodillos con vibración incorporada añaden un estímulo extra que para algunas personas relaja más el músculo con menos tiempo de rodado, pero multiplican el precio del rodillo básico por cuatro o cinco. Si ya usas con regularidad un rodillo manual y notas que te falta más intensidad, puede compensar; como primera compra, no suele ser necesario.",
        ],
      },
    ],
    checklist: [
      "Densidad según tu experiencia: media para empezar, firme si ya toleras bien la presión",
      "Tamaño según el uso: largo para espalda y piernas, corto o mini para zonas puntuales o viaje",
      "Set con accesorios solo si vas a usarlos de verdad (pies, cuello, antebrazo)",
      "Vibración o motor solo si ya entrenas con un rodillo manual y buscas más intensidad",
    ],
    faq: [
      {
        q: "¿El rodillo de espuma duele al usarlo?",
        a: "Cierta molestia es normal, sobre todo la primera vez o en zonas muy cargadas, pero un dolor agudo o que empeora no lo es: en ese caso hay que parar y bajar la presión (por ejemplo con un rodillo más blando) o consultar a un fisioterapeuta.",
      },
      {
        q: "¿Cada cuánto conviene usarlo?",
        a: "No hay una cifra única, pero usarlo unos minutos después de entrenar, o en días de descanso sobre zonas cargadas, es una pauta razonable para la mayoría de personas. Un uso diario intenso sobre la misma zona no acelera la recuperación y puede llegar a irritar el tejido.",
      },
    ],
    products: [
      {
        asin: "B0F61TYLZC",
        title: "McBlast 4 Uds. Set Masaje Fascial con Rodillo y Bola",
        note: "El más barato de la selección, set combinado de rodillo y bola de masaje.",
        img: "https://m.media-amazon.com/images/I/81bIh8HPgGL._AC_SF480,480_.jpg",
        price: "8",
        rating: "3,9★",
      },
      {
        asin: "B071P2MQ5D",
        title: "Amazon Basics Rodillo de espuma moteada de alta densidad",
        note: "Marca genérica de confianza, densidad alta a un precio moderado.",
        img: "https://m.media-amazon.com/images/I/91yuQpw++mL._AC_SF480,480_.jpg",
        price: "18",
        rating: "4,5★",
      },
      {
        asin: "B0CZ391FD1",
        title: "unycos Rodillo de Espuma EPP para Masaje Muscular, 30x15 cm",
        note: "Formato mini, fácil de guardar en un cajón o llevar de viaje.",
        img: "https://m.media-amazon.com/images/I/81x3O70dY+L._AC_SF480,480_.jpg",
        price: "8",
        rating: "4,1★",
      },
      {
        asin: "B09GYRVZRY",
        title: "MAGIC SELECT Rodillo Masajeador de Espuma para Terapia, 33x14 cm",
        note: "Tamaño estándar de densidad media, buen punto de entrada sin sorpresas.",
        img: "https://m.media-amazon.com/images/I/719-fEuv3SL._AC_SF480,480_.jpg",
        price: "10",
        rating: "4,3★",
      },
      {
        asin: "B0BT7Z7S5F",
        title: "unycos Rodillo para Masajes Musculares 33x14 cm",
        note: "Densidad media similar a la anterior, de una marca con buen historial en accesorios de fitness.",
        img: "https://m.media-amazon.com/images/I/71BM+qFOV2L._AC_SF480,480_.jpg",
        price: "11",
        rating: "4,4★",
      },
      {
        asin: "B0CC5R1X49",
        title: "Foam Roller Largo DRUNA, 60x15 cm",
        note: "Formato largo de 60 cm, más estable para trabajar la espalda entera.",
        img: "https://m.media-amazon.com/images/I/81bNLshevYL._AC_SF480,480_.jpg",
        price: "15",
        rating: "4,6★",
      },
      {
        asin: "B0D7W8CR59",
        title: "MAGIC SELECT Rodillo Masajeador de Espuma, 45x15 cm",
        note: "Tamaño intermedio entre el estándar y el largo de la selección.",
        img: "https://m.media-amazon.com/images/I/610kUnMIGeL._AC_SF480,480_.jpg",
        price: "19",
        rating: "4,5★",
      },
      {
        asin: "B09GK66VY5",
        title: "Qveetry 6 en 1 Rodillos de Espuma con Palos y Bolas de Masaje",
        note: "Set con varios accesorios además del rodillo principal, para cubrir más zonas.",
        img: "https://m.media-amazon.com/images/I/71GSpvdv9mL._AC_SF480,480_.jpg",
        price: "23",
        rating: "4,2★",
      },
      {
        asin: "B07LGCCG36",
        title: "KALAHARI Foam Roller Kit 3 en 1 + eBook de ejercicios",
        note: "Incluye guía de ejercicios en PDF, útil si nunca has usado un rodillo antes.",
        img: "https://m.media-amazon.com/images/I/71il6+dyZuL._AC_SF480,480_.jpg",
        price: "27",
        rating: "4,3★",
      },
      {
        asin: "B075RS2F73",
        title: "Odoland Rodillo de espuma 5 en 1 con puntos de activación",
        note: "Relieve con puntos de presión en vez de superficie lisa, para tensión más localizada.",
        img: "https://m.media-amazon.com/images/I/71bUQui3U9L._AC_SF480,480_.jpg",
        price: "28",
        rating: "4,4★",
      },
      {
        asin: "B0040EGNIU",
        title: "TriggerPoint Grid Rodillo de Espuma",
        note: "El modelo más conocido y mejor valorado del segmento medio, densidad firme que mantiene la forma con el uso.",
        img: "https://m.media-amazon.com/images/I/71baGwPZOWL._AC_SF480,480_.jpg",
        price: "34",
        rating: "4,7★",
      },
      {
        asin: "B00X6D060W",
        title: "RAD Herramienta de liberación miofascial de espuma de alta densidad",
        note: "Formato distinto, pensado para movilidad y recuperación además del rodado clásico.",
        img: "https://m.media-amazon.com/images/I/71O6GAxUuuL._AC_SF480,480_.jpg",
        price: "51",
        rating: "4,6★",
      },
      {
        asin: "B08LDYHPXN",
        title: "Wave Series Wave Roller, con vibración Bluetooth",
        note: "Gama alta: vibración con varias frecuencias y control por Bluetooth, el más caro de la selección.",
        img: "https://m.media-amazon.com/images/I/614L3RmQnJL._AC_SF480,480_.jpg",
        price: "149",
        rating: "4,3★",
      },
    ],
  },
];

const ARTICLES = [
  {
    slug: "como-montar-un-gimnasio-en-casa-desde-cero",
    title: "Cómo montar un gimnasio en casa desde cero",
    dek: "El orden en el que conviene comprar cada cosa, y por qué no hace falta gastar todo el presupuesto el primer mes.",
    img: "/assets/img/blog/como-montar-un-gimnasio-en-casa-desde-cero.jpg",
    updated: "2026-09-16",
    body: [
      "Montar un gimnasio en casa desde cero da la tentación de comprarlo todo de golpe, pero el orden en el que incorporas cada pieza importa tanto como qué piezas eliges: empezar por lo básico evita comprar equipamiento que acaba sin usar.",
      "El orden que mejor funciona para la mayoría es este: primero una esterilla y un set de bandas elásticas (barato, versátil, sirve para movilidad y activación desde el primer día); después unas mancuernas ajustables o un par de pesos medios, que cubren la mayoría de ejercicios de fuerza de tren superior e inferior; y por último, si el hábito ya está asentado, un banco de entrenamiento, que multiplica los ejercicios posibles con las mancuernas que ya tienes.",
      "Comprar el banco antes que las mancuernas es un error habitual: sin peso suficiente que levantar, el banco apenas aporta nada extra sobre entrenar en el suelo o de pie.",
      "Un truco simple para no sobrecomprar: espera a notar qué ejercicio concreto se te queda corto con lo que ya tienes antes de añadir la siguiente pieza. Si lo que te falta es progresar en press de banca, compra el banco; si lo que te falta es variedad de tirón, prioriza las bandas con ancla de puerta.",
      "En las guías de este sitio (mancuernas, esterillas, bandas, banco y accesorios de cardio) desarrollamos cada pieza por separado con más detalle.",
    ],
  },
  {
    slug: "errores-comunes-empezar-a-entrenar-en-casa",
    title: "5 errores comunes al empezar a entrenar en casa",
    dek: "Cosas fáciles de arreglar que no cuestan dinero, antes de pensar en comprar más equipamiento.",
    img: "/assets/img/blog/errores-comunes-empezar-a-entrenar-en-casa.jpg",
    updated: "2026-09-11",
    body: [
      "Antes de gastar en más material, merece la pena revisar si el problema es de espacio o de rutina, no de equipo: varios de los errores más comunes se arreglan sin comprar nada.",
      "1. Entrenar siempre en el mismo hueco de suelo duro. Sin una esterilla o base de amortiguación, el impacto repetido en rodillas y muñecas se acumula sesión tras sesión, aunque no se note al principio.",
      "2. Comprar una sola mancuerna o banda \"para probar\". Sin margen de progresión, en pocas semanas esa pieza se queda corta y hay que comprar otra vez: mejor un sistema pensado para crecer contigo desde el principio.",
      "3. No fijar un ajuste correcto en los accesorios (comba demasiado larga, banco en la altura equivocada). Un accesorio mal ajustado no solo incomoda: cambia la técnica del ejercicio y reduce su efecto.",
      "4. Guardar el equipamiento fuera de la vista. Si la esterilla y las mancuernas están en un armario cerrado, hace falta un paso extra de decisión cada día para entrenar. Dejarlas a la vista, aunque sea en un rincón pequeño, reduce la fricción para empezar.",
      "5. Cero planificación de progresión. Ninguna pieza de equipamiento, por buena que sea, sustituye a subir peso o resistencia poco a poco. Anotar qué se hizo la última sesión evita quedarse estancado por comodidad.",
    ],
  },
  {
    slug: "cuanto-gastar-en-equipamiento-de-fitness-casero",
    title: "¿Cuánto merece la pena gastar en equipamiento de fitness casero?",
    dek: "Dónde están los saltos de calidad reales y dónde el precio ya no compra nada nuevo.",
    img: "/assets/img/blog/cuanto-gastar-en-equipamiento-de-fitness-casero.jpg",
    updated: "2026-09-09",
    body: [
      "No hay una cifra única válida para todo el mundo, pero sí hay tramos de precio donde el salto de calidad es real y tramos donde ya no se nota tanto.",
      "El primer salto importante está entre no tener nada y tener lo básico: esterilla, un set de bandas de varios niveles y un par de mancuernas de peso medio. Ese salto es el que más impacto tiene en si el hábito de entrenar en casa arranca o no, independientemente de la marca.",
      "El segundo salto, más caro, está en la durabilidad y la progresión: mancuernas ajustables en vez de fijas, un banco con capacidad de peso alta, bandas sin látex que no se degradan. Este tramo compensa sobre todo si ya llevas meses entrenando de forma constante y notas que el equipo básico se te queda corto.",
      "A partir de cierto precio, lo que se paga de más suele ser diseño, marca o accesorios extra, no rendimiento adicional: los criterios que de verdad importan (capacidad de peso, agarre, ajuste) ya estaban cubiertos en el tramo anterior.",
      "La pregunta que más ayuda a decidir no es \"¿cuánto cuesta?\" sino \"¿llevo ya varios meses entrenando de forma constante?\". Si la respuesta es sí, invertir en el tramo de mejor durabilidad y progresión se amortiza rápido; si acabas de empezar, lo básico bien elegido es suficiente para no gastar de más en algo que todavía no sabes si vas a mantener.",
    ],
  },
  {
    slug: "aprovechar-espacio-pequeno-para-entrenar",
    title: "Cómo aprovechar un espacio pequeño para entrenar en casa",
    dek: "No hace falta una habitación entera: con un par de metros cuadrados bien pensados es suficiente.",
    img: "/assets/img/blog/aprovechar-espacio-pequeno-para-entrenar.jpg",
    updated: "2026-09-08",
    body: [
      "La falta de espacio es la excusa más común para no entrenar en casa, pero la mayoría de rutinas de fuerza y cardio caben en 2-3 metros cuadrados si el equipamiento se elige pensando en eso desde el principio.",
      "Prioriza equipamiento plegable o apilable: mancuernas ajustables en lugar de una fila de pares fijos, un banco plegable en lugar de uno fijo, bandas elásticas que caben en un cajón. La diferencia entre un gimnasio en casa que dura y uno que se abandona suele estar en si hay que \"montar\" mucho antes de poder empezar a entrenar.",
      "Un hueco vertical (detrás de una puerta, dentro de un armario bajo) es tan válido como un hueco horizontal para guardar esterilla y bandas: no hace falta reservar suelo permanentemente si el equipamiento es ligero y rápido de sacar.",
      "Si el suelo es de baldosa o parqué, una esterilla de buen tamaño no solo protege las articulaciones: también protege el suelo de golpes de mancuernas o del roce del banco, algo que en un piso de alquiler conviene cuidar especialmente.",
      "Por último, la iluminación y la ventilación del rincón elegido influyen más de lo que parece en si apetece entrenar ahí o no: un hueco luminoso y ventilado, aunque sea pequeño, se usa más que una esquina oscura y cerrada por grande que sea.",
    ],
  },
];

// Un producto destacado por categoría, para el bloque "Lo más recomendado"
// que aparece en todas las páginas (ver featuredProductsSection en lib.js).
// Se reutilizan los datos ya cargados en GUIDES para no duplicar imagen/precio.
function pickFeatured(guideSlug, asin) {
  const g = GUIDES.find((x) => x.slug === guideSlug);
  const p = g.products.find((x) => x.asin === asin);
  return { ...p, category: g.slug, categoryTitle: g.title };
}

const FEATURED = [
  pickFeatured("mancuernas-ajustables", "B0GJ61RH56"),
  pickFeatured("esterillas-yoga", "B0CYBGQVZH"),
  pickFeatured("bandas-elasticas", "B0H4GMM4TX"),
  pickFeatured("banco-entrenamiento", "B09V8BNQSZ"),
  pickFeatured("accesorios-cardio", "B0G2MSQNCJ"),
  pickFeatured("kettlebells", "B076QJY2FN"),
  pickFeatured("rodillos-espuma-recuperacion", "B0040EGNIU"),
];

module.exports = { GUIDES, ARTICLES, FEATURED };
